"""add team_key_players table and team_features key_players columns

Revision ID: 173944d13806
Revises: 261ea278ef95
Create Date: 2026-07-28 14:59:52.308170

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "173944d13806"
down_revision: str | None = "261ea278ef95"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "team_key_players",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("team_id", sa.UUID(), nullable=False),
        sa.Column("season_year", sa.Integer(), nullable=False),
        sa.Column("player_rank", sa.Integer(), nullable=False),
        sa.Column("player_id", sa.String(length=100), nullable=False),
        sa.Column("player_name", sa.String(length=150), nullable=False),
        sa.Column("ws_48", sa.Float(), nullable=False),
        sa.Column("per", sa.Float(), nullable=False),
        sa.Column("mpg", sa.Float(), nullable=False),
        sa.Column("computed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "team_id", "season_year", "player_rank", name="uq_team_key_players_team_season_rank"
        ),
    )
    op.add_column("team_features", sa.Column("key_players_available", sa.Integer(), nullable=True))
    op.add_column("team_features", sa.Column("key_players_per_combined", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("team_features", "key_players_per_combined")
    op.drop_column("team_features", "key_players_available")
    op.drop_table("team_key_players")
    # ### end Alembic commands ###
