"""add fixtures.odds_provider_external_id

Revision ID: 1bd3a835a107
Revises: dcb097536d58
Create Date: 2026-07-28 12:25:19.746361

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1bd3a835a107"
down_revision: str | None = "dcb097536d58"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "fixtures", sa.Column("odds_provider_external_id", sa.String(length=100), nullable=True)
    )
    op.create_unique_constraint(
        "uq_fixtures_sport_odds_external_id", "fixtures", ["sport_id", "odds_provider_external_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_fixtures_sport_odds_external_id", "fixtures", type_="unique")
    op.drop_column("fixtures", "odds_provider_external_id")
    # ### end Alembic commands ###
