"""add team_features.season_point_diff

Revision ID: 261ea278ef95
Revises: 1bd3a835a107
Create Date: 2026-07-28 12:59:27.144215

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "261ea278ef95"
down_revision: str | None = "1bd3a835a107"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("team_features", sa.Column("season_point_diff", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("team_features", "season_point_diff")
    # ### end Alembic commands ###
