"""init schema

Revision ID: 29c85029ecef
Revises:
Create Date: 2026-07-28 01:18:14.787240

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "29c85029ecef"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sports",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("model_type", sa.String(length=100), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=150), nullable=True),
        sa.Column("expo_push_token", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "leagues",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("sport_id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("country", sa.String(length=100), nullable=True),
        sa.Column("tier", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["sport_id"],
            ["sports.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "models_registry",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("sport_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.String(length=100), nullable=False),
        sa.Column("artefact_path", sa.String(length=255), nullable=False),
        sa.Column("rps_score", sa.Float(), nullable=True),
        sa.Column("accuracy", sa.Float(), nullable=True),
        sa.Column("trained_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["sport_id"],
            ["sports.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.String(length=255), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_table(
        "user_preferences",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("default_sport_id", sa.UUID(), nullable=True),
        sa.Column("default_min_odds", sa.Float(), nullable=True),
        sa.Column(
            "odds_format",
            sa.Enum("DECIMAL", "FRACTIONAL", "AMERICAN", name="odds_format"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["default_sport_id"],
            ["sports.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "teams",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("sport_id", sa.UUID(), nullable=False),
        sa.Column("league_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("short_name", sa.String(length=50), nullable=True),
        sa.Column("external_id", sa.String(length=100), nullable=True),
        sa.ForeignKeyConstraint(
            ["league_id"],
            ["leagues.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sport_id"],
            ["sports.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "fixtures",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("sport_id", sa.UUID(), nullable=False),
        sa.Column("league_id", sa.UUID(), nullable=False),
        sa.Column("home_team_id", sa.UUID(), nullable=False),
        sa.Column("away_team_id", sa.UUID(), nullable=False),
        sa.Column("kickoff_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum("SCHEDULED", "LIVE", "COMPLETED", name="fixture_status"),
            nullable=False,
        ),
        sa.Column("season", sa.String(length=20), nullable=False),
        sa.ForeignKeyConstraint(
            ["away_team_id"],
            ["teams.id"],
        ),
        sa.ForeignKeyConstraint(
            ["home_team_id"],
            ["teams.id"],
        ),
        sa.ForeignKeyConstraint(
            ["league_id"],
            ["leagues.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sport_id"],
            ["sports.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "player_injury_status",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("sport_id", sa.UUID(), nullable=False),
        sa.Column("player_id", sa.String(length=100), nullable=False),
        sa.Column("team_id", sa.UUID(), nullable=False),
        sa.Column("player_name", sa.String(length=150), nullable=False),
        sa.Column(
            "status",
            sa.Enum("OUT", "GTD", "PROBABLE", "ACTIVE", name="injury_status"),
            nullable=False,
        ),
        sa.Column("return_date", sa.Date(), nullable=True),
        sa.Column("salary_rank", sa.Integer(), nullable=True),
        sa.Column(
            "source", sa.Enum("ROTOWIRE", "BALLDONTLIE", name="injury_source"), nullable=False
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["sport_id"],
            ["sports.id"],
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "fixture_live_state",
        sa.Column("fixture_id", sa.UUID(), nullable=False),
        sa.Column("home_score", sa.Integer(), nullable=False),
        sa.Column("away_score", sa.Integer(), nullable=False),
        sa.Column("match_minute", sa.Integer(), nullable=True),
        sa.Column("period", sa.String(length=20), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("last_updated_utc", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["fixture_id"],
            ["fixtures.id"],
        ),
        sa.PrimaryKeyConstraint("fixture_id"),
    )
    op.create_table(
        "odds",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("fixture_id", sa.UUID(), nullable=False),
        sa.Column("bookmaker", sa.String(length=100), nullable=False),
        sa.Column("market", sa.Enum("H2H", "SPREAD", "TOTAL", name="odds_market"), nullable=False),
        sa.Column("home_odds", sa.Float(), nullable=True),
        sa.Column("draw_odds", sa.Float(), nullable=True),
        sa.Column("away_odds", sa.Float(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["fixture_id"],
            ["fixtures.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "outcomes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("fixture_id", sa.UUID(), nullable=False),
        sa.Column("home_score", sa.Integer(), nullable=False),
        sa.Column("away_score", sa.Integer(), nullable=False),
        sa.Column(
            "result", sa.Enum("HOME_WIN", "DRAW", "AWAY_WIN", name="match_result"), nullable=False
        ),
        sa.Column("settled_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["fixture_id"],
            ["fixtures.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "predictions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("fixture_id", sa.UUID(), nullable=False),
        sa.Column("model_version", sa.String(length=100), nullable=False),
        sa.Column("home_prob", sa.Float(), nullable=False),
        sa.Column("draw_prob", sa.Float(), nullable=True),
        sa.Column("away_prob", sa.Float(), nullable=False),
        sa.Column(
            "confidence_tier",
            sa.Enum("HIGH", "MEDIUM", "LOW", name="confidence_tier"),
            nullable=False,
        ),
        sa.Column("expected_value", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["fixture_id"],
            ["fixtures.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "team_features",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("team_id", sa.UUID(), nullable=False),
        sa.Column("fixture_id", sa.UUID(), nullable=False),
        sa.Column("elo_rating", sa.Float(), nullable=True),
        sa.Column("attack_str", sa.Float(), nullable=True),
        sa.Column("defence_str", sa.Float(), nullable=True),
        sa.Column("form_pts_5", sa.Float(), nullable=True),
        sa.Column("xg_for_5", sa.Float(), nullable=True),
        sa.Column("xg_against_5", sa.Float(), nullable=True),
        sa.Column("days_since_last_match", sa.Integer(), nullable=True),
        sa.Column("home_win_rate", sa.Float(), nullable=True),
        sa.Column("away_win_rate", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["fixture_id"],
            ["fixtures.id"],
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("team_features")
    op.drop_table("predictions")
    op.drop_table("outcomes")
    op.drop_table("odds")
    op.drop_table("fixture_live_state")
    op.drop_table("player_injury_status")
    op.drop_table("fixtures")
    op.drop_table("teams")
    op.drop_table("user_preferences")
    op.drop_table("refresh_tokens")
    op.drop_table("models_registry")
    op.drop_table("leagues")
    op.drop_table("users")
    op.drop_table("sports")
    # ### end Alembic commands ###
