"""frozen_picks.candidates

Revision ID: 466edcbf4be8
Revises: 5767cd391219
Create Date: 2026-09-09 22:40:16.190329

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "466edcbf4be8"
down_revision: str | None = "5767cd391219"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "frozen_picks",
        sa.Column("candidates", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("frozen_picks", "candidates")
    # ### end Alembic commands ###
