"""frozen_picks

Revision ID: 5767cd391219
Revises: b7badfaec3cd
Create Date: 2026-09-04 23:23:09.108542

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5767cd391219"
down_revision: str | None = "b7badfaec3cd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "frozen_picks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("fixture_id", sa.UUID(), nullable=False),
        sa.Column("market", sa.String(length=32), nullable=True),
        sa.Column("selection", sa.String(length=32), nullable=True),
        sa.Column("line", sa.Float(), nullable=True),
        sa.Column("probability", sa.Float(), nullable=True),
        sa.Column("odds", sa.Float(), nullable=True),
        sa.Column("feature_completeness", sa.Float(), nullable=True),
        sa.Column("model_version", sa.String(length=100), nullable=True),
        sa.Column("prediction_created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "frozen_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("frozen_reason", sa.String(length=16), nullable=False),
        sa.ForeignKeyConstraint(["fixture_id"], ["fixtures.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("fixture_id", name="uq_frozen_picks_fixture"),
    )
    op.create_index("ix_frozen_picks_frozen_at", "frozen_picks", ["frozen_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_frozen_picks_frozen_at", table_name="frozen_picks")
    op.drop_table("frozen_picks")
    # ### end Alembic commands ###
