"""team_features.recent_form

Revision ID: b7badfaec3cd
Revises: f1a7c3d9e820
Create Date: 2026-08-25 11:13:27.330220

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b7badfaec3cd"
down_revision: str | None = "f1a7c3d9e820"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("team_features", sa.Column("recent_form", sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("team_features", "recent_form")
    # ### end Alembic commands ###
