"""add models_registry roi_simulation

Revision ID: d7cdee97c00f
Revises: 173944d13806
Create Date: 2026-07-28 21:08:17.487555

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d7cdee97c00f"
down_revision: str | None = "173944d13806"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("models_registry", sa.Column("roi_simulation", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("models_registry", "roi_simulation")
    # ### end Alembic commands ###
