"""add fixtures.external_id

Revision ID: dcb097536d58
Revises: 29c85029ecef
Create Date: 2026-07-28 09:44:17.335690

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dcb097536d58"
down_revision: str | None = "29c85029ecef"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("fixtures", sa.Column("external_id", sa.String(length=100), nullable=True))
    op.create_unique_constraint(
        "uq_fixtures_sport_external_id", "fixtures", ["sport_id", "external_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_fixtures_sport_external_id", "fixtures", type_="unique")
    op.drop_column("fixtures", "external_id")
    # ### end Alembic commands ###
