"""fixtures.withdrawn: distinguish a withdrawn fixture from a called-off one

Revision ID: faa1ecc4c1ac
Revises: ba36f6870577
Create Date: 2026-08-12 22:57:04.064119

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "faa1ecc4c1ac"
down_revision: str | None = "ba36f6870577"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "fixtures", sa.Column("withdrawn", sa.Boolean(), server_default="false", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("fixtures", "withdrawn")
    # ### end Alembic commands ###
